### ISSUE TITLE
IDX is not defined(sha256_transform)

### ISSUE THREAD

**Issue by ghost** [progranism/Open-Source-FPGA-Bitcoin-Miner#28]
I am implementing this code on Xilinx FPGA for learning purposes but there is a small issue if you can help me. 
```
always @ (posedge clk)
	begin
		if (!feedback)
		begin
		
			tx_hash[`IDX(0)] <= rx_state[`IDX(0)] + HASHERS[64/LOOP-6'd1].state[`IDX(0)];
			tx_hash[`IDX(1)] <= rx_state[`IDX(1)] + HASHERS[64/LOOP-6'd1].state[`IDX(1)];
			tx_hash[`IDX(2)] <= rx_state[`IDX(2)] + HASHERS[64/LOOP-6'd1].state[`IDX(2)];
			tx_hash[`IDX(3)] <= rx_state[`IDX(3)] + HASHERS[64/LOOP-6'd1].state[`IDX(3)];
			tx_hash[`IDX(4)] <= rx_state[`IDX(4)] + HASHERS[64/LOOP-6'd1].state[`IDX(4)];
			tx_hash[`IDX(5)] <= rx_state[`IDX(5)] + HASHERS[64/LOOP-6'd1].state[`IDX(5)];
			tx_hash[`IDX(6)] <= rx_state[`IDX(6)] + HASHERS[64/LOOP-6'd1].state[`IDX(6)];
			tx_hash[`IDX(7)] <= rx_state[`IDX(7)] + HASHERS[64/LOOP-6'd1].state[`IDX(7)];
		
		end
	end

```
IDX is not defined that's the error which i am facing. Is it just a variable ? or what? Thanks

**Comment by fpgaminer** [comment]
It's a macro, defined here:

https://github.com/progranism/Open-Source-FPGA-Bitcoin-Miner/blob/fd76bc932ae04be2b27be769871105c4678af9dc/src/sha256_transform.v#L26

**Comment by ghost** [comment]
Thanks for your reply. I solved the above issue with your help. Now I have one last issue that you call some functions which are not defined like `altpll	altpll_component`  in **module main_pll function** & `s1	s1_blk	(rx_w[479:448], s1_w);` in **module sha256_transform**. I am facing now these errors. Thanks for your help

**Comment by fpgaminer** [comment]
`s1` is defined in here: https://github.com/progranism/Open-Source-FPGA-Bitcoin-Miner/blob/master/src/sha-256-functions.v

`altpll` is an Altera megafunction provided by Altera's (Intel's) Quartus compiler.

**Comment by ghost** [comment]
I am using Xilinx Vivado compiler and my FPGA board will be one of the Xilinx boards so how I can modify altpll for my compiler.

**Comment by ghost** [comment]
Is there anyway, that I can replace this IP **altpll** for my compiler.
